export const favorites = [
  "God of War",
  "The Witcher 3: Wild Hunt",
  "Terraria",
  "HELLDIVERS™ 2",
  "Hades",
  "Risk of Rain 2",
  "Kingdoms and Castles",
  "ANIMAL WELL",
  "The Last of Us™ Part I",
  "Kingdom Come: Deliverance II",
  "Chivalry 2",
  "Marvel Rivals",
  "It Takes Two",
  "DAVE THE DIVER",
  "Assassin's Creed",
  "Assassin's Creed II",
  "Assassin's Creed Brotherhood",
  "Assassin's Creed Revelations",
  "Assassin's Creed III Remastered",
  "Assassin's Creed IV Black Flag",
]
